### ISSUE TITLE
When at main page nav bar should highlight home not submit

### ISSUE THREAD

**Issue by fishcharlie** [thayer11/Project-2#4]
When you click on the home nav item it highlights submit as the active nav bar item. This is confusing since I'm not on the submit page I'm on the home page.

<img width="1383" alt="screen shot 2016-07-22 at 2 16 38 pm" src="https://cloud.githubusercontent.com/assets/860375/17070037/11391736-5017-11e6-880c-dddaf2a4a42e.png">

**Comment by thayer11** [comment]
Ahhh yes, good catch. It's changed.
